name: Refresh Data Pipeline

on:
  push:
  pull_request:
  schedule:
    - cron: "45 23 * * 5"

jobs:
  routine-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Poetry using pip
      run: |
        python -m pip -r requirements.txt

    - name: Run Python script pushing data to motherduck
      env:
        motherduck_token: ${{ secrets.motherduck_token }}

    - name: Execute routine task
      run: |
        python src/etl/refresh_data.py  