tasks:
  - source: src/etl/initialize_load.py
    product:
      nb: src/products/initialize_load.ipynb
      data: msft_database.duckdb

  - source: src/etl/eda.ipynb
    product:
      nb: src/products/eda.ipynb

  - source: src/etl/lstm.ipynb
    product:
      nb: src/products/lstm.ipynb

  - source: src/etl/arima.ipynb
    product:
      nb: src/products/arima.ipynb
